### ISSUE TITLE
Change error type when profile is not found

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/I-Talent#123]
- current get profile implementation returns a 404 that looks concerning in console.
- the front end handles this 404 gracefully but the console print out (error) can be scary for users
- it's not broken but to avoid confusion we should improve this

**_NOTE:_** This can be reproduced by deleting profile form DB and going to profile setup but changing URL steps to 3, 4, or 5. The browser console should display the 404 error.

**Comment by mo-5** [comment]
I think the API should always return profile not found if the profile is not found in the database. It's a good coding practice overall. One way we can change this is to return an empty profile of the user ID exists but the profile doesn't.

**Comment by dynamic11** [comment]
This relates to issue #171
