### ISSUE TITLE
Docker container for frontend failing on Run

### ISSUE THREAD

**Issue by SukhsimranpreetSekhon** [CDH-Studio/I-Talent#132]
- Docker fails to run the `upskill_web-ant` container (frontend)
- the container crashes Run
- this issue has been observed since pull request #118 
- we suspect it is due to update of react-scripts from `3.4.0` to `3.4.1`

*** Disclaimer: If you run the container in interactive mode, the web app will work. Unsure at the moment for this case. ****

**Comment by dynamic11** [comment]
Changing react-scripts back to `3.4.0` seems to have resolved the issue. Will finalize PR and push change shortly.
