### ISSUE TITLE
Add "Expand for Description" on Experience cards (User Profile)

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#134]
- See Kat for mockup
- Add Antd expand component under each experience entry

**Comment by dynamic11** [comment]
@KateAThornley can you add the screenshot of the issue to this please

**Comment by TrevorBivi** [comment]
https://puu.sh/FHrTs.png Here's what she sent me. I'll attach a link to how the real thing looks in the PR
![descriptionMockUp](https://user-images.githubusercontent.com/30152653/81328765-74945500-906b-11ea-8653-180c29123d85.png)
