### ISSUE TITLE
Fix "skillOptions.map is not a function" bug on Search Page

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#135]
- To reproduce: docker-compose up --build, stop upskill_backend from running, load home page of app, error should occur.

**Comment by BenJeau** [comment]
Fixed by #227 by adding default props! But similar errors are present when searching, clicking on advance search, viewing profile, and admin. Edit profile is good surprisingly (except one page that throws an error). Should fixing the other pages be a part of this issue?

**Comment by BenJeau** [comment]
I'll open new issues regarding the other errors and will close this one.
