### ISSUE TITLE
Investigate Bizchart vs Antv G2

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/I-Talent#140]
- we are currently using bizchart for data visualization
- antd has a sister project for visualization called antv G2
- investigate if switching over is necessary/needed

**This is very low priority**

**Comment by BenJeau** [comment]
Just saw, bizcharts is using Antv G2 under the hood

**Comment by dynamic11** [comment]
I actually knew that. I forgot to tell you. It has some enhancements I believe

**Comment by BenJeau** [comment]
Bizcharts is a react version of Antv G2, from what I'm seeing Antv G2 does not have components - I think
