### ISSUE TITLE
Incorrect substantive dropdown options 

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#158]
**Describe the bug**
In the profile form, employment data section, the dropdown for "Substantive" is showing an incorrect list.  

**To Reproduce**
1. Go to 'Edit Profile"
2. Go to "Employment data form"
3. Click on 'Substantive' drop down
4. See incorrect options

**Expected behavior**
Dropdown options should be:

- Term
- Indeterminate
- Casual

**Comment by MenaMachado** [comment]
Hi Kate, I don't know if you've fixed this but I don't see the correct options on the dev server. Thanks

**Comment by KateAThornley** [comment]
Hi Mena,
I merged a fix for this a while ago and we all have the right values in our local dev environments but the live database just needs to be updated to show the correct values:)
Thanks!

**Comment by MenaMachado** [comment]
Ok, sounds good, I will reassign to Ali.

**Comment by dynamic11** [comment]
UAT DB updated
