### ISSUE TITLE
Add option to delete account

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#175]
**Is your feature request related to a problem? Please describe.**
A user may want to delete their account from I-Talent (maybe because they are leaving the GC, or they just want to start their account over from scratch)

**Describe the solution you'd like**
At the bottom of the sidebar of the Edit Profile pages, there could be a "Advanced Profile Settings" button that opens a page/module on screen. The module or page would then offer a button to delete one's account (there should also be a confirmation popup for the user to select cancel or confirm delete account). 

**Describe alternatives you've considered**
I was thinking of putting a "Delete my account" button directly at the bottom of the sidebar but It might look more out of place than putting an Advanced Profile Settings button. Also if we have an APS button we can group other functions into that module or page when we find a need to add them.

**Comment by BenJeau** [comment]
Also, HR/Admin should be able to delete accounts
