### ISSUE TITLE
Modify GEDs profile search result to work with french

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/I-Talent#176]
**Describe the bug**
The square GEDs profile cards are not wide enough for French translation so need to modify the UI

**To Reproduce**
1. Go to "create profile"
2. Click on "Step 1"
3. Change language to french
4. See truncated text in GEDs results

**Expected behavior**
The design should show most of the text in English and french

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/81304210-c37dc280-904a-11ea-96e8-1d2122f346bf.png)

**Comment by BenJeau** [comment]
I don't think this is fixed, the button text is still truncated (in French)

**Comment by MenaMachado** [comment]
I must have closed it by mistake
