### ISSUE TITLE
Fix Profile Translation for Skills (wait to see if it happens again)

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#181]
**Describe the bug**
When searching for a skill in I-Talent, once clicked on the relevant profile the skill's categories are shown in French (when language preference is set to English) while the rest of the profile is in English.

**To Reproduce**
1. Go to I-Talent home page and make sure language is set to English in topnav
2. Search for a skill you know is on Mena's profile
3. Click on Mena's result card to view her profile
4. Scroll down to Skills card
5. See how categories are in French but the rest of the profile is displayed correctly in English

**Expected behavior**
The categories on the skill card should be displayed in English while the language preference is set to English (not French)

**Screenshots**
![Screen Shot 2020-05-07 at 10 57 32 AM](https://user-images.githubusercontent.com/43188335/81309997-8ec13980-9051-11ea-96cd-360ce85c8f08.png)

**Comment by MenaMachado** [comment]
This seems to be corrected since yesterday's update.  My profile from search results is now showing the categories in english.

![image](https://user-images.githubusercontent.com/49656364/81437970-fb176800-9139-11ea-9cb3-2d95b3021a3f.png)
