### ISSUE TITLE
Add generic label when branch field is left empty on profile

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#187]
**Describe the bug**
When a user doesnt want to put their branch down ion their profile (i.e. they don't select to sync with GEDS), the field is displayed as empty when it should have a generic no value message

**To Reproduce**
1. Create a profile from scratch (dont sync to GEDS)
2. Visit your profile (view your profile)
3. Should see empty branch

**Expected behavior**
If a field is not displayed on the profile there should be a generic "no value" message

**Comment by MenaMachado** [comment]
In UAT, my Branch and Address are appearing since yesterday's update

![image](https://user-images.githubusercontent.com/49656364/81437236-d373d000-9138-11ea-9062-cb7f005dd239.png)
