### ISSUE TITLE
Sort and display Developer goals and School dropdowns in alphabetical order

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#189]
**Describe the solution you'd like**
During profile setup or edit, when users search for developmental goals (in the Personal Growth Interests section) or schools (in the Qualification section), the dropdown options should be displayed alphabetically (ascending).

**Additional context**
Screenshot showing non-alphabetical ordering of developmental goals:
<img width="978" alt="Screen Shot 2020-05-07 at 11 28 35 AM" src="https://user-images.githubusercontent.com/43188335/81313459-e5307700-9055-11ea-9005-1af1e99309ad.png">
Screenshot showing non-alphabetical ordering of schools:
<img width="965" alt="Screen Shot 2020-05-07 at 11 29 11 AM" src="https://user-images.githubusercontent.com/43188335/81313535-faa5a100-9055-11ea-9739-946be20c8729.png">

**Comment by s-glmxmd** [comment]
**Describe the solution you'd like**
The tags for Competencies, Skills, Mentorship Skills and Developmental Goals on the profile page should be ordered alphabetically (ascending).

**Additional context**
Screenshot showing non-alphabetical ordering of developmental goals:

![Screen Shot 2020-05-14 at 9 10 03 AM](https://user-images.githubusercontent.com/31967843/81938917-a0f82600-95c3-11ea-89a5-e78a02ffe132.png)

**Comment by BenJeau** [comment]
I think in the new backend, we are returning the options data pre-sorted, will just need to double-check once it is merged within dev

**Comment by BenJeau** [comment]
So the dropdown options are now sorted since #425, but not the tags in the profile view, will create a PR for that
