### ISSUE TITLE
clearing localStorage breaks displaying many profile fields

### ISSUE THREAD

**Issue by TrevorBivi** [CDH-Studio/I-Talent#194]
**Describe the bug**
When you clear your local storage localStorage.getItem("lang") will return undefined instead of 'en' or 'fr'. Various profile components use this value to decide which text to display from the backend. As a result many fields display the default not specified value or appear blank.

**To Reproduce**

1. Set value in your profile such as first language or career mobility
2. Clear your browsing data 
3. Values will now be displayed incorrectly

**Expected behavior**
The site should fallback to displaying the english version of values

**Screenshots**

**Additional context**
Updating your chosen language will fix the issue

**Comment by dynamic11** [comment]
I believe the PR #170 resolve some of this. Does it include all issues you found?
@MohamedRadwan any input?

**Comment by mo-5** [comment]
Yes, I set the default language to English if localStorage.getItem("lang") is null. If the issue is still reoccurring reopen #170. This is a temporary fix until I implement an api to store the language in the database along with the user information.

**Comment by TrevorBivi** [comment]
> I believe the PR #170 resolve some of this. Does it include all issues you found?
> @MohamedRadwan any inpute?

Whoops yep I didn't realise that PR fixed so much stuff, I think he fixed all the problems. I'll close this issue
