### ISSUE TITLE
profile/edit/qualification site freezing and unexpected behavior relating to ongoing checkmark

### ISSUE THREAD

**Issue by TrevorBivi** [CDH-Studio/I-Talent#208]
**Describe the bug**
When the user goes to the profile/edit/qualification page multiple experience items will have ongoing checked even though they shouldn't be. If the user presses a checkmark to set an item as ongoing the browser will freeze up. If a new item is added some of these checkbox's the end date field's labels may flicker between "End date" and "* End date" and the browser will quickly freeze up

**To Reproduce**
1. You probably don't need to, but you might need remove yourself from the db and add least two items to these lists on the account setup, that's what I did
2. Go to the profile/edit/qualification page. You'll probably see ongoing checkmarks being set incorrectly
2. Add a new item or press an ongoing checkmark and the page should freeze

**Expected behavior**
The page should not freeze and ongoing checkmarks should be set to what the user saved them as

**Screenshots**

**Additional context**

**Comment by dynamic11** [comment]
I don't experience a freeze up but I do see the endate not showing up even though it should
I can look into it since i wrote it 🤦

**Comment by dynamic11** [comment]
I looked into this and realized that on first load of the page the data is fin but if yo reload the end date disappears. @BenJeau and @KateAThornley can you both test for this issue on your local environments?

**Comment by TrevorBivi** [comment]
I'm having trouble figuring out exactly why I'm getting a freeze, I'm more used to class 
components. But I think that I'm getting into a state inside of ExperienceFormView and EducationFormView where useEffect calls toggleEndDate and this causes useEffect to be called again over and over

**Comment by KateAThornley** [comment]
> I looked into this and realized that on first load of the page the data is fin but if yo reload the end date disappears. @BenJeau and @KateAThornley can you both test for this issue on your local environments?

Yeah, as soon as I reload the page the date above ongoing disapears but its still saved correctly in my db
