### ISSUE TITLE
Add "Print results" button to results page

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#215]
**Is your feature request related to a problem? Please describe.**
Some managers may want to a physical copy of all resumes of the employees that match their search results, thus we need a way to easily print them out.

**Describe the solution you'd like**
A button on the results page/in the results page sidebar that prints nicely formated resumes (sumaries of the profile page) of each applicant that matched the search criteria/is displayed on the results page.

**Comment by mo-5** [comment]
We can make the backend generate a pdf based on the HTML. There are node packages that can do this for us.

**Comment by mo-5** [comment]
Currently working on this ticket and this is how the printout looks like any opinions? 
![image](https://user-images.githubusercontent.com/21133129/102843654-9ca4ae80-43d7-11eb-8997-fdb901196757.png)

**Comment by MenaMachado** [comment]
The format looks acceptable
