### ISSUE TITLE
Getting white screen of death when I click on "Talent" in side nav in Edit Profile

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#216]
**Describe the bug**
Consistently getting white screen when clicking on "Talent" in side nav

**To Reproduce**
1. Go to 'Edit Profile'
2. Click on 'Talent' on side nav
3. Getting white screen of death

**Expected behavior**

Clicking on Talent should bring me to the talent section of the form

**Screenshots**
![image](https://user-images.githubusercontent.com/49656364/81435313-a540c100-9135-11ea-8a06-e930b7197b95.png)

**Additional context**

**Comment by BenJeau** [comment]
fixed by #245
