### ISSUE TITLE
Searching own name sends no results on results page

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#218]
If a user creates a profile and searches for themselves by name, the results page return no results. However, if a user searches for another user with a profile by name, it returns the correct user profile card. 

**To Reproduce**
1. Go to 'search page'
2. Click on 'search'
3. Enter own name in 'name' field
4. Click on search
5. Own user profile card not displayed

**Expected behavior**
As a user, I should be able to search for my own profile by name

**Screenshots**
![image](https://user-images.githubusercontent.com/49656364/81444441-2489c100-9145-11ea-966b-2a71ed6e5dc9.png)

**Additional context**
If I search by any other field provided, it will return users own profile

**Comment by BenJeau** [comment]
Hi @MenaMachado, I'm not sure if this is an issue or just the way it's supposed to work. I realized that when you create an account, you can input your 'own name', but the system will also get your name from your credentials. Search will only return results based on the name you provided and not the one from your credentials (if I understand correctly @dynamic11).

If we want the search to return results based on the name from our credentials, I can make the changes.

**Comment by dynamic11** [comment]
@BenJeau I was actually aware of this issue. But I didn't think it would affect search.  I think we should default the persons name to the one given in credentials like we so with the email. The user shouldn't be able to change it. @MenaMachado what do you think about this from HR perspective? Will people have a problem with not being able to customize their name?

**Comment by MenaMachado** [comment]
If I recall, I responded to this by email to Ali.  I agree with Ali, we should use the name from the email credentials.

**Comment by dynamic11** [comment]
if you search first name (ex. Ali) we get results but if you search first+last (ex. Ali Nouri) we don't get results. This is probably due to our algorithm searching for "Ali Nouri" in first name and last name without breaking up the name.
