### ISSUE TITLE
Add and Clean EsLinter

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#227]
**Is your feature request related to a problem? Please describe.**
For future developers working with I-Talent, the code on the front-end should followed a stylalized guide for consistency purposes.

**Describe the solution you'd like**
Installing EsLinter and handling all errors that violate guidelines from eslint in each component view and controller

**Additional context**

**Comment by KateAThornley** [comment]
Cleaning: 
- components/skillCards
- components/profileCards
- components/admin/categoryTable
- components/admin/competencyTable
- components/admin/dashboardGraphs
- components/admin/skillTable
- components/admin/userTable

**Comment by dynamic11** [comment]
we have a PR in for ESlint. how does this Issue relate to that?

**Comment by KateAThornley** [comment]
> we have a PR in for ESlint. how does this Issue relate to that?

I can't find the issue, do you have the number by chance?

**Comment by TrevorBivi** [comment]
> we have a PR in for ESlint. how does this Issue relate to that?

I think that branch is unneeded. I think that that PR was just adding eslint and running the command to fix issues that can be fixed automatically. Our configuration for eslint has changed slightly since and we're running automated fixing as we do additional manual fixing in the new branch.

**Comment by BenJeau** [comment]
Cleaned: 
- src/components/layouts
- src/components/basicInfo
- src/components/careerInterest
- src/components/changeLang
- src/components/employeeSummary
- src/components/formLabelTooltip
- src/components/landingLayout
- src/components/experience
- src/pages
- src/components/sideNav
- src/components/talentManagement
- src/components/searchBar
- src/components/searchFilter
- src/components/projects
- src/components/resultsLayout
- src/components/profileSkeleton
- src/routes

**Comment by TrevorBivi** [comment]
I'll edit this comment to keep it up to date with what I'm cleaning:

- services\frontend-v3\src\components\profileForms
- services\frontend-v3\src\components\customAvatar
- services\frontend-v3\src\components\developmentalGoals
- services\frontend-v3\src\components\education
- services\frontend-v3\src\components\errorResult
- services\frontend-v3\src\components\resultsCard
- services\frontend-v3\src\components\admin\statCards

**Comment by TrevorBivi** [comment]
Yet another one of my official Canada accounts is acting up again. Now Mena can't add my ms online account to the teams chat, so I'm locked out of it right now. If someone wants to appoint me stuff here to reformat I'll do it. Otherwise, I'll keep looking at other bugs while I wait to be able to communicate properly again.

**Comment by BenJeau** [comment]
Oof, that's not fun, you can do any of the files that are left, I know the files in the root of src haven't been touched yet.

**Comment by TrevorBivi** [comment]
> 
> 
> Oof, that's not fun, you can do any of the files that are left, I know the files in the root of src haven't been touched yet.

Alright then, I'll do the files in /src. What about  src/pages a src/functions and src/routes? They probably wouldn't take too long for me to do as well.

**Comment by BenJeau** [comment]
I'm doing the ones in src/routes right now, and I did the src/pages. The ones in src/functions haven't been touched yet

**Comment by BenJeau** [comment]
Do you need help with any that are left @TrevorBivi?

**Comment by TrevorBivi** [comment]
No thanks. I've done the simple changes I can now. Now I gotta make sure I don't brake login while making some more changes then I think I'm done
