### ISSUE TITLE
Clean and organize backend 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#232]
Clean up backend code and update all the packages and remove any errors. This will allow for scalability and better maintenance in the long run. This will improve development for future developers as well since it will be easier for people to go through the code.

**Comment by dynamic11** [comment]
Please define what you mean by "clean up".
I would say "clean up getUserName endpoint" or "Refactor ......"

**Comment by mo-5** [comment]
I am going through refactoring the routes and the API folder. I am not changing the core functionality of each function but rather changing the structure of where the functions and how they get called. I am just going through everything so it might be a large pull request. I could make a list of everything and update it once I am done 

- Making a specific directory for routes instead of some being in API folder and some in the server.js file. In the routes directory I will add a separate file for each feature/function so that its more organized if we need to add more api end points later on. 

- Moved all database files to a database directory 

- Refactoring all the functions that have undefined variables or return null. I will make a list and update the comment.

- Fixing some eslint issues as well
