### ISSUE TITLE
Wrong form title for Qualifications

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/I-Talent#233]
**Describe the bug**
on the qualifications form the title is "personal growth interests". Should be "qualifications"

**To Reproduce**
1. Go to 'edit profile'
2. Click on 'Qualifications' on sidebar
4. See heading of form is "personal growth interests"

**Expected behavior**
the heading should be  "qualifications"

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/81578395-bcbbbc00-9378-11ea-899c-052ece573c23.png)

**Comment by MenaMachado** [comment]
Other titles will also need to change.  I was planning to create a small table with "old" and new title and discuss it with the client beforehand
