### ISSUE TITLE
Have search fields persisted after searching

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/I-Talent#249]
**Is your feature request related to a problem? Please describe.**
After searching for a profile, the fields are blank

**Describe the solution you'd like**
I'd like to have the information that I entered still present on the page

**Describe alternatives you've considered**
Maybe using redux, but it's probably overkill for this. We should probably just parse the url and set that as the initial data

**Comment by dynamic11** [comment]
I agree with your solution. I will follow along with this. Once it is merged I will go in and restyle the side bar slightly.

**Comment by BenJeau** [comment]
Should there be a general search on the results page? Just saw that there wasn't one
