### ISSUE TITLE
Unable to sign up as a new user

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#286]
**Describe the bug**
Once you sign in as a new user it takes you directly to the search page. 

**To Reproduce**
1) Delete your database
2) Sign in

**Expected behavior**
To be able to sign up for a new account. 

**Screenshots**

![Annotation 2020-05-25 110702](https://user-images.githubusercontent.com/21133129/82824886-2909e580-9e78-11ea-95fc-a839e07b2ad2.png)

**Comment by dynamic11** [comment]
maybe related to issue #248

**Comment by BenJeau** [comment]
I'm also getting a blank screen after refreshing the search page, once I "signed up"

Edit: disregard this, the blank screen happened because of one of my privacy chrome extension

**Comment by BenJeau** [comment]
Related to the backend Dockerfile and npm to yarn move
