### ISSUE TITLE
On Edit Profile page, update content list in sidebar to match content list in my profile page

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#293]
**Is your feature request related to a problem? Please describe.**
On the Edit Profile page, the list of items on the sidebar does not provide sufficient detail.  It should provide subheadings similar to the sidebar on the user's my profile page. 

**Additional context**
![image](https://user-images.githubusercontent.com/49656364/82835829-2799e680-9e93-11ea-82ea-c333f37a73a7.png)

![image](https://user-images.githubusercontent.com/49656364/82835861-439d8800-9e93-11ea-987c-fb492085a65c.png)

**Comment by BenJeau** [comment]
On dev, this has been added via https://github.com/CDH-Studio/UpSkill/pull/267
