### ISSUE TITLE
White Screen on Results Page (Development)

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#295]
**Describe the bug**
When searching in Fuzzy Search for something on the live dev app for I-Talent, the results page renders for a second then before the cards can fill the layout the page turns white with nothing displayed.

**To Reproduce**
1. Go to http://mytalent-frontend-dev-mytalent.apps.dev.openshift.ised-isde.canada.ca/secured/home
2. Search for anything in the general search bar
3. See how results page is blank

**Expected behavior**
After searching, should return a page with results cards matching search criteria

**Comment by BenJeau** [comment]
I'm not getting any white screens anymore using the steps to reproduce above, what are the steps to get a white screen now?
