### ISSUE TITLE
Add footers in pages to include a link to Terms and Conditions of Use, Privacy Policy, About, and Email Contact

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/I-Talent#301]
**Is your feature request related to a problem? Please describe.**
Since we are adding a privacy policy, we should probably put a link to it in the application. In the footer would be a great place and we could store other information/links

**Describe the solution you'd like**
Have a footer in every pages containing the privacy policy and other info

**Additional context**
#289

**Comment by MenaMachado** [comment]
The footer should be very similar to this example (except for the Canada logo).  The contact email and content to follow.

The footer should be in grey with links to the following:

- About I-Talent        -Help/Contact us           -   Terms & Conditions of use            -Privacy       



![image](https://user-images.githubusercontent.com/49656364/85757294-56e38380-b6dd-11ea-9595-1fced396a7b6.png)

![image](https://user-images.githubusercontent.com/49656364/85757681-b04bb280-b6dd-11ea-9afb-f6f39bac2ada.png)

**Comment by KateAThornley** [comment]
Updates for meeting before final commit and review:

![image](https://user-images.githubusercontent.com/43188335/87169892-9d6cdc80-c29e-11ea-9191-6a4185e3c13a.png)
![image](https://user-images.githubusercontent.com/43188335/87169904-9fcf3680-c29e-11ea-86a4-bb17086d551c.png)
![image](https://user-images.githubusercontent.com/43188335/87169910-a2319080-c29e-11ea-8581-a0970782ef75.png)

**Comment by MenaMachado** [comment]
Hi Kate, can you replace with the following wording:

- About
- Terms and Conditions of Use

And, add a tab for "Help/Contact Us

Tips should redirect users to the "help" tab
