### ISSUE TITLE
Viewing other profiles on the dev/uat server gives a blank screen

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/I-Talent#327]
**Describe the bug**
When searching for another person in the dev/uat server, and view another person's profile, the profile seems empty (gives a white screen)

**To Reproduce**
1. Search for another user
2. Click on a user
3. See white screen

**Expected behavior**
The profile should be present and show its information instead of a white screen

**Screenshots**
![image](https://user-images.githubusercontent.com/22248828/83534579-0783ac00-a4bf-11ea-8514-9b672afd2eb4.png)

**Additional context**
This is the error thrown in the console, there's not a lot of information since it is a production build
https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20fr%7D&args[]=

According to this error, it seems to be related to the locale of the data. It is trying to render a variable where it is an object in the format `{en: '', fr: ''}` instead of a string.

**Interesting discovery**
The following profiles doesn't seem to trigger that error
- Sagal Maxamud (a65e508c-78e1-11ea-940a-0a580a80031b)
- Mohamed radwan (ad8ddb54-8f00-11ea-8f87-0a580a8105a0)
- trevor bivi (5a85a374-8ed8-11ea-8383-0a580a8105a0)
- Kate Thornley (568454c2-75d9-11ea-a19a-0a580a80031b)
- Mary Doe (faba08aa-ffe3-11e9-8d71-362b9e155667)

**Comment by dynamic11** [comment]
as discussed in the meeting this could be caused by branch.
I can look into it today

**Comment by BenJeau** [comment]
Seems to be fixed by #328
