### ISSUE TITLE
ASC-7 - Error and exception handling 

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#344]
**ID:** ASC-7 - Error and exception handling 

**Description**

The   primary objective of error handling and logging is to provide a useful   reaction by the user, administrators, and incident response teams. The objective is not to create massive amounts of logs, but high-quality logs,   with more signal than discarded noise.  

High quality logs will often contain sensitive data, and must be protected as   per local data privacy laws or directives.       

A verified application should (1) not collect or log sensitive information if   not specifically required, (2) should ensure all logged information is   handled securely and protected as per its data classification, (3) and should   ensure that logs are not forever, but have an absolute lifetime that is as   short as possible. If logs contain sensitive data, the logs become some of   the most sensitive information held by the application and thus very   attractive to attackers.      

**Error Handling Best Practices **

 1. Display Generic Error Messages    
a. Error messages should not reveal details about the internal state of the   application. For example, file system path and stack information should not   be exposed to the user through error messages.   

 2. No Unhandled Exceptions    
a. Given the languages and frameworks in use for web application development,   never allow an unhandled exception to occur. Error handlers should be   configured to handle unexpected errors and gracefully return controlled   output to the user.    

3. Suppress Framework Generated Errors   
a. Your development framework or platform may generate default error  messages. These should be suppressed or replaced with customized error   messages as framework generated messages may reveal sensitive information to  the user.   

4. Logs Errors and Exceptions    
a. Content must not be exposed but error and exceptions must be logged       

Sources / References:   
1. Securing Web Application Technologies [SWAT] Checklist https://software-security.sans.org/resources/swat
--

**Evidence Required**
Please provide: 
1. List of error messages displayed when error/exception occurs. 
2. Log sample containing errors / exception

**Comment by MenaMachado** [comment]
I think you may have been involved in error handling of our application. Can you say which of these best practices we have applied?

**Comment by mo-5** [comment]
Yes, we are currently displaying a generic error message. Nothing is exposed from the application standpoint. This issue is addressed since we are following the best practices for handling errors.

**Comment by BenJeau** [comment]
As for the logging, what we have right now is basic logging - for the backend we are printing it in the terminal/console (this information is available in openshift) - as for the frontend, I don't think we are logging any errors, they are only shown to the user

**Comment by MenaMachado** [comment]
@MohamedRadwan, this is the last security control for which I need to provide a response.  Can I ask you to work on this as a priority?

**Proper error and exception handling system**
I think as a first step we need to set ourselves up with properly catching and handling errors and exceptions. It's possible we've already done some of this work. I think Ben worked on this a bit.  I found this article that might be helpful.  https://www.toptal.com/nodejs/node-js-error-handling. 

**Log sample containing errors / exception**

- We also need a solution to log and store the errors and exceptions when they occur.  I know we are using morgan but I'm not sure if it is set up to log these. 
- We need to provide the types of events we are logging.   Ex:  Input validation failures e.g. protocol violations, unacceptable encodings, invalid parameter names and value; Output validation failures e.g. database record set mismatch, invalid data encoding; Application errors and system events e.g. syntax and runtime errors, connectivity problems, performance issues. It's possible we are logging events in separate systems. 
- We need to explain where the logs are stored (e.g postgres database) and who has access to the logs. 
- The application logs must record "when, where, who and what" for each event but at the same time we should avoid logging sensitive data. 

**List of error messages displayed when error/exception occurs**
-  We need to provide a list of error messages that we display as proof that they don't reveal sensitive information.  If it's easier we can provide screenshots of our error messages.

**Comment by MenaMachado** [comment]
Hi I just saw this  #1093 
I think it's also linked to issue #256

**Comment by mo-5** [comment]
@BenJeau I am not sure how much you have looked into error tracking. I looked into Prometheus and it seems like it only captures API calls like morgan

**Comment by BenJeau** [comment]
@MohamedRadwan If I'm quite honest, I don't remember a lot of it, but I think I looked into this during the summer https://github.com/siimon/prom-client and https://prometheus.io/docs/prometheus/latest/installation/#using-docker, Prometheus seems to just be a system where we would report from within our code manually to it - kind of analytics but for our backend, and maybe error reporting. 

But I don't understand how it is used in ISED, I think ISED uses Grafana for the visualization of the metrics and logs, @MenaMachado am I right or did I pull it out of thin air? If so, would you have more info on that or the link to the ISED version of this tool? I can't seem to find the URL, I know I had it at some point, but don't know where it is

**Comment by MenaMachado** [comment]
I looked up my old conversations in teams.  You can set up Prometheus  endpoint and it scrapes to provide metrics that would be displayed on a grafana dashboard which would be interesting. Jim had sent me this https://medium.com/teamzerolabs/node-js-monitoring-with-prometheus-grafana-3056362ccb80.  But I think we still need a logging tool to catch errors.

**Comment by BenJeau** [comment]
@MenaMachado I remember accessing a website that was like sonarqube and openshift, but it was grafana and I remember it was hosted on ISED, would you by chance have that? I don't recall how I got that URL haha

**Comment by MenaMachado** [comment]
There is this on our wiki that lists the tools we use https://wiki.ised-isde.canada.ca/display/RDADC/Cloud+supported+tools+and+technologies
