### ISSUE TITLE
ASC-8 LOG MANAGEMENT

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#345]
**ID:** ASC-8 LOG MANAGEMENT

**Description**
Log management is essential to ensuring that computer security records are stored in sufficient detail for an appropriate period of time. Routine log analysis is beneficial for identifying security incidents, policy violations, fraudulent activity, and operational problems. Logs are also useful when performing auditing and forensic analysis, supporting internal investigations, establishing baselines, and identifying operational trends and long-term problems.

Application logging should be consistent within the application, consistent across an organization's application portfolio and use industry standards where relevant, so the logged event data can be consumed, correlated, analyzed and managed by a wide variety of systems. 

Logging Best Practices 
1. Log All Relevant Business Activities 
a. Engagement of business unit is highly suggested 
2. Log All Security Relevant Activities 
Where possible, always log: 
a. Input validation failures 
b. Output validation failures 
c. Authentication successes and failures 
d. Authorization (access control) failures 
e. Session management failures 
f. Application errors and system events 
g. Application and related systems start-ups and shut-downs, and logging initialization (starting, stopping or pausing) 
h. Use of higher-risk functionality e.g. addition or deletion of users, changes to privileges, assigning users to tokens, adding or deleting tokens, use of systems administrative privileges, access by application administrators, all actions by users with administrative privileges, access to payment cardholder data, use of data encrypting keys, key changes, creation and deletion of system-level objects, submission of user-generated content - especially file uploads 
i. Access to Sensitive Data 
j. Legal and other opt-ins 
3. Data to Exclude from Logs 
The following should not usually be recorded directly in the logs, but instead should be removed, masked, sanitized, hashed or encrypted: 
a. Application source code 
b. Session identification values (consider replacing with a hashed value if needed to track session specific events) 
c. Access tokens 
d. Sensitive personal data and some forms of personally identifiable information (PII) e.g. health, government identifiers, vulnerable people 
e. Authentication passwords 
f. Database connection strings 
g. Encryption keys and other master secrets 
h. Bank account or payment card holder data 
i. Data of a higher security classification than the logging system is allowed to store 
j. Commercially-sensitive information 
k. Information it is illegal to collect in the relevant jurisdictions 
l. Information a user has opted out of collection, or not consented to e.g. use of do not track, or where consent to collect has expired 
4. Log Events Attributes 
The application logs must record "when, where, who and what" for each event. 
* When 
** Log date and time (international format) 
** Event date and time 
* Where 
** Application identifier e.g. name and version 
** Application address e.g. workstation identity, local device identifier 
** Service e.g. name and protocol 
** Geolocation 
* Who (human or machine user) 
** Source address e.g. user's device/machine identifier, user's IP address, 
** User identity (if authenticated or otherwise known) e.g. user database table primary key value, user name, license number 
* What 
** Type of event 
** Severity of event 
5. Store Logs Securely 
a. Logs should be stored and maintained appropriately to avoid information loss or tampering by intruder. 
b. Log retention should follow the retention policy set forth by the Department to meet regulatory requirements and provide enough information for forensic and incident response activities. 
c. While logging errors and auditing access is important, sensitive data should never be logged in an unencrypted form 
6. Leverage Risk-Based Authentication 
a. Monitoring anomalous login attempts (e.g., based on IP address, time of day, etc.) is another system-side measure that can be used to defend against online guessing attacks. Monitoring should be capable of detecting both large numbers of failed logins on individual accounts as well as failed logins across many accounts. 

Sources / References: 
1. Securing Web Application Technologies [SWAT] Checklist https://software-security.sans.org/resources/swat 
2. Logging Cheat Sheet (https://www.owasp.org/index.php/Logging_Cheat_Sheet) 
3. Guide to Computer Security Log Management NIST 800-92 (https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-92.pdf) 

**Evidence Required**

Please   provide:      

1. List of all security-related event types logged 
2. List of all relevant business-related event types also logged 
3. Documentation explaining log management 
a. Where are the logs stored? 
b. How are the logs stored? 
c. Who has access to logs? 
d. What is the log review process: who is responsible to review, how often, what to do in case anomalies are identified? 
4. Log sample

**Comment by mo-5** [comment]
I think we should focus on this if it's a blocker for production since it will take some time to implement. If my understanding is correct and based on what I have seen previously we need to log every event or action made by the user and display them to the admins. We could discuss this at our next meeting if we would want to create a new database for this or use the same database since it will quickly get full of data with more users on the system.
