### ISSUE TITLE
ASC-9 DATA & CREDENTIAL PROTECTION AT REST 

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#346]
**ID:**ASC-9 DATA & CREDENTIAL PROTECTION AT REST 

**Description**
Data at rest is data that is not actively moving from device to device or network to network such as data stored on a hard drive, laptop, flash drive, or archived/stored in some other way. Data protection at rest aims to secure inactive data stored on any device or network. 

Data Protection at Rest Best Practices 
1. Encrypt Protected B data at rest 
a. Encryption is the front-line defense for defending data at rest. It limits access to those with the right keys - locking out anyone who doesn't have them. It removes any worry about retirement of disks and voids the threat of physical compromise of the cloud environment (even if someone walks away with the data drive from the cloud service provider's data center, they won't have access). 
b. Consult Cryptographic Algorithms for Unclassified, Protected A, and Protected B information (https://www.cse-cst.gc.ca/en/node/1831/html/26515) 
2. Partially Encrypt Data 
a. Column-level encryption solutions encrypt some information in the database while other information is left in the clear. 
3. Manage Keys and Policies 
a. Encryption by itself is not the answer; Keys, policies and certificates must be actively managed, making sure those protection devices do not fall into the wrong hands. 
b. When keys are stored in your system they must be properly secured and only accessible to the appropriate staff on a need to know basis. 
4. Get Rid of Sensitive Information Quickly 
a. When the application must store sensitive data, make sure that the information is erased as soon as possible. 
b. Reduce time to live for temporary data. 
5. Leverage Strong Access Control 
a. Do not authorize external parties access to the data, including the cloud services providers. Denying cloud provider access to information prevents cloud administrators or compromised cloud admin accounts from accessing the data. 
6. Employ Directory Services Infrastructures and Group Access Controls 
a. Tie data access policies to a Directory Services Infrastructure (e.g., Active Directory) and use group access controls to encrypted data from within the organization. 
b. Tying data access/encryption to a directory services infrastructure helps to further secure on-boarding and off-boarding procedures. 
7. Monitor and Audit 
a. Monitor who, what, where, when and how data is accessed from within databases and applications, as well as at the OS/file system level. 
b. Monitor and collect information on access to sensitive information. 
c. Collect and monitor the data for unauthorized access attempts to determine if an attack is underway - alert where appropriate. 

Credential Protection at Rest Best Practices 
1. Store Credentials Using a Strong, Iterative, Salted Hash 
a. Do not store credentials in plaintext. 
b. Credentials must be stored using secure hashing techniques with strong algorithms. 
** Consult Cryptographic Algorithms for Unclassified, Protected A, and Protected B information (https://www.cse-cst.gc.ca/en/node/1831/html/26515) 
2. Disable Data Caching Using Cache Control Headers and Autocomplete 
a. Browser data caching should be disabled using the cache control HTTP headers or meta tags within the HTML page. 
b. Sensitive input fields, such as the login form, should have the autocomplete=off setting in the HTML form to instruct the browser not to cache the credentials. 

Protecting Static Resources 
1. Use random filename or GUIDs as filenames. 
2. Do not store sensitive static content in directory paths that are part of the application’s own’s file hierarchy. Instead, store this content in a directory that is fully outside of the application’s directory structure and proxy the application’s access to that data through a handler that can properly authorize and log any access to the file. 

Sources / References: 
1. Cryptographic Algorithms for Unclassified, Protected A, and Protected B information (https://www.cse-cst.gc.ca/en/node/1831/html/26515) 
2. Securing Web Application Technologies [SWAT] Checklist https://software-security.sans.org/resources/swat

**Evidence Required**
Please provide: 
1. Documentation explaining the data at rest protection strategy 

The documentation must identify: 
- Where the sensitive data is stored (e.g., database, GDDocs, etc.) – include the sensitive data’s location in the DFD (see ASC-1) 
- The mechanisms used to protect data at rest 
- The mechanisms used to protect stored credentials 
- The encryption key management strategy

**Comment by MenaMachado** [comment]
@MohamedRadwan  we will eventually need to move our DB to AWS.  In the meantime, can you say which of these best practices we have applied?

**Comment by mo-5** [comment]
I think we need to open separate issues to address some of these points. 

- Monitor and Audit
   - We would need to develop an Audit software which is a requirement for protected B information (to my knowledge). This will keep track of the user's usage and the data they request. There are node packages that would be able to perform this for us. We would just need to research them and see which one would be applicable. 

> a. Monitor who, what, where, when and how data is accessed from within databases and applications, as well as at the OS/file system level.
> b. Monitor and collect information on access to sensitive information.
> c. Collect and monitor the data for unauthorized access attempts to determine if an attack is underway - alert where appropriate.

- To my knowledge currently, we are not encrypting any of the data in the database. This might need a ticket for itself as well. If I remember correctly AWS has encryption to DB on rest setting that can be toggled to on. 

- We are not in charge of credentials and logging in so we wouldn't need to worry about this point.
