### ISSUE TITLE
ASC-10 DATA IN TRANSIT 

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#347]
**ID:** ASC-10 DATA IN TRANSIT

**Description**

Data in transit, or data in motion, is data actively moving from one location to another such as across the internet or through a private network. Data protection in transit is the protection of this data while it’s traveling from network to network or being transferred from a local storage device to a cloud storage device – wherever data is moving, effective data protection measures for in transit data are critical as data is often considered less secure while in motion. 

Data Protection in Transit Best Practices 
1. Use HTTPS Everywhere 
a. Ideally, HTTPS should be used for your entire application. If you have to limit where it's used, then HTTPS must be applied to any authentication pages as well as to all pages after the user is authenticated. If sensitive information (e.g. personal information) can be submitted before authentication, those features must also be sent over HTTPS. 
2. Disable HTTP Access for All Protected Resources 
a. For all pages requiring protection by HTTPS, the same URL should not be accessible via the insecure HTTP channel. 
3. Use the Strict-Transport-Security Header (HSTS) 
a. The Strict-Transport-Security header ensures that the browser does not talk to the server over HTTP. This helps reduce the risk of HTTP downgrade attacks as implemented by the sslsniff tool. 
4. Securely Exchange Encryption Keys 
a. If encryption keys are exchanged or pre-set in your application then any key establishment or exchange must be performed over a secure channel 
5. Disable Weak TLS Configuration on Servers 
a. Weak ciphers must be disabled on all servers. For example, SSL v2, SSL v3, and TLS protocols prior to 1.2 have known weaknesses and are not considered secure. 
b. Disable the NULL, RC4, DES, and MD5 cipher suites. 
c. Ensure all key lengths are greater than 128 bits, use secure renegotiation, and disable compression. 
6. Using an encrypted channel (SSL/TLS) to send and receive data protects against eavesdropping attacks. 
a. It prevents an attacker from intercepting sensitive information such as usernames, passwords, session IDs, and login forms. It also guards against cross-site request forgery. 
b. Secure the transmission from browser to web app / web app to other resources internal or external. 
c. Secure “inter-zone traffic” when data comes from a less restricted zone to a higher restricted zone 
d. Secure transmission of credentials. 
** Protecting only the login process or highly sensitive transactions is a good start. However, what many applications fail to protect are session IDs, which are just as sensitive as username and password. Only protecting the login but then transmitting the protected data over insecure channel doesn’t do much good when an attacker read it off the wire.

Sources / References: 
1. Cryptographic Algorithms for Unclassified, Protected A, and Protected B information (https://www.cse-cst.gc.ca/en/node/1831/html/26515) 
2. Securing Web Application Technologies [SWAT] Checklist https://software-security.sans.org/resources/swat 
3. HTTP Strict Transport Security Cheat Sheet (https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet) 
4. Guidance on security configuring network protocols (https://www.cse-cst.gc.ca/en/node/1830/html/26507) 

**Evidence Required**
Please provide: 
1. Documentation explaining the data in transit protection strategy 
The documentation must identify: 
- When does the application force the use of HTTPS? 
- Does the application use HSTS to enforce HTTPS when necessary? 
- Describe how encryption keys are managed and protected? 
- Are the secure and HttpOnly flags set in the cookies? 
2. Quality Assurance (QA) tests report 
a. Qualys tool 
b. ssl scanner 
3. Pen testing report

**Comment by mo-5** [comment]
Are the SSL/TLS certificates provided by IT security? We could use let's encrypt but that requires an update to the certificate every 90 days.

**Comment by mo-5** [comment]
Testing our current domain on SSL labs results in a B evaluation. As per security requirements, we need to drop support for all  TLS protocols prior to 1.2. 

I have attached the evaluation below if the link becomes invalid please rerun the analysis on ssllabs.com

https://www.ssllabs.com/ssltest/analyze.html?d=italent%2ddev.apps.dev.openshift.ised%2disde.canada.ca&s=52.60.221.171

**Comment by MenaMachado** [comment]
@MohamedRadwan, same with this one. Can you confirm which of these best practices we’ve applied?

**Comment by mo-5** [comment]
So we are following all the standards for this ticket except for one. 
> Disable Weak TLS Configuration on Servers
> a. Weak ciphers must be disabled on all servers. For example, SSL v2, SSL v3, and TLS protocols prior to 1.2 have known weaknesses and are not considered secure.
> b. Disable the NULL, RC4, DES, and MD5 cipher suites.
> c. Ensure all key lengths are greater than 128 bits, use secure renegotiation, and disable compression.

We need to disable Weak ciphers which is why we are getting a B evaluation. After the weak ciphers are disabled we should be receiving a score A- and above which should be good for a protect B application. 

![image](https://user-images.githubusercontent.com/21133129/89715723-b1772d00-d975-11ea-90c7-52f84ec6be12.png)

I know how to do this with HAproxy but I have not used open shift so I am not sure how complicated it would be. Please let know if you have any question.
