### ISSUE TITLE
View Profile Button after Setup Not Redirecting to Profile

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#361]
**Describe the bug**
When done setting up profile on UAT clicking the 'View Profile' button pushes user to /profile/undefined and stays loading.

**To Reproduce**
1. Go to UAT (/secured/profile/create/step/8)
2. Click on ''View Profile'
4. See how page gets stuck on loading skeleton with a route of /undefined

**Expected behavior**
Should bring user directly to their newly created profile page.

**Comment by BenJeau** [comment]
fixed by #360
