### ISSUE TITLE
Search filter for Branch does not appear to be working properly

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#366]
**Describe the bug**

**To Reproduce**
1. Go to Advance Search
2. Select 235 Queen in Location field
3. On Search results page, select Human Resources Branch in Branch Field
4. See "no results found"

**Expected behavior**
There are a few employees with profiles in HR. Those should have appeared on the results page.

**Screenshots**
![image](https://user-images.githubusercontent.com/49656364/84196410-25788000-aa6e-11ea-9491-fd51ad4492cf.png)

![image](https://user-images.githubusercontent.com/49656364/84196447-345f3280-aa6e-11ea-8c83-0f015cf1482f.png)

**Comment by BenJeau** [comment]
Seems to be fixed by #425, please feel free to re-open if this is not the case
