### ISSUE TITLE
Create a warning/confirmation message for when employees toggle switch from hidden to show OL, Talent management, and security information on pr

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#373]
**Issue:**

Some of the information recorded in a users profile is classified protected A. I-Talent is designed to give employees full control over profile visibility. They can decide what information in their profile they want to hide or show to other ISED employees logged in to I-Talent by using the toggle switch for each card.  In this case, there is a risk that an employee will unhide certain information by mistake. 

**Solution**

- Set all toggle switches to hidden for all cards. Whenever someone toggles the switch from hide to show, the user should be prompted with a warning/confirmation message.

- Create a modal dialog box for the warning/confirmation message

Title in modal box: Privacy
Message: "Are you sure you want to make this information visible to all I-Talent members?"

Provide commit  buttons for yes or no

If they select yes, make information visible to all members. 
If they select no, keep information private to user only and greyed.

**Comment by dynamic11** [comment]
**we can do something like this:**
1)
![image](https://user-images.githubusercontent.com/11470442/84790888-e2636300-afbf-11ea-8761-e03952b143be.png)

2) or a simple popover message saying "your info is now publicly visible"
