### ISSUE TITLE
Add/Edit/Delete Links to supporting documents under Education and Experience sections

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#435]
Employees will want to add links to documents such copies of certificates, resumes, projects material, etc.  Employees will also want to provide links to specific posters in jobs.gc.ca to show the jobs they qualified in.  They may also want to provide links to git repositories, etc. 

Rather than upload documents that take space, it is better for employees to save their documents in GCDOCs and provide links to those documents in I-Talent. 

Instructions

**For Education**

- For each education (e.g Ed 1) Users will want to add/edit/remove links to the following documents: diploma, transcript, publication list
- The display name for the URL can be: diploma, transcript, publication list
- There should be only one diploma,one transcript, and one publication list per Education
- Suggestion is to add a button for add link similiar to "add item"

**For Experience**
- For each experience (e.g EX 1 ) Users will want to add/edit/remove links to the following documents: Awards and recognition, Reference letter, Work Sample. 

The display name can be Work sample 1, Work sample 2, Work sample 3, etc. 

They may also want to add links to sites like Github, Bitbucket, Wiki, etc. 

![image](https://user-images.githubusercontent.com/49656364/89462730-de400000-d73b-11ea-9f66-007c483ecae3.png)
![image](https://user-images.githubusercontent.com/49656364/89463080-63c3b000-d73c-11ea-8f79-d78a15966569.png)

Below are screens shots from GC Directory as an example for design, requirements and wording.

Edit/Delete Links

![image](https://user-images.githubusercontent.com/49656364/85893762-7b189080-b7c1-11ea-967e-68e73c22fe4c.png)

![image](https://user-images.githubusercontent.com/49656364/85893360-bebeca80-b7c0-11ea-8b81-43ce70988660.png)

![image](https://user-images.githubusercontent.com/49656364/85893404-d007d700-b7c0-11ea-8865-a515f21afc01.png)

![image](https://user-images.githubusercontent.com/49656364/85893417-d6964e80-b7c0-11ea-9d7e-981ce6f5ac59.png)

![image](https://user-images.githubusercontent.com/49656364/85893427-db5b0280-b7c0-11ea-93ef-ef9dbe5cbd4e.png)

**Comment by BenJeau** [comment]
To give you some inspiration (in linkedin)
![image](https://user-images.githubusercontent.com/22248828/89436767-affafa00-d714-11ea-967f-731a4e30f042.png)
 Maybe instead of showing a preview of the website, just show the favion of the website or show an icon representing its category?
