### ISSUE TITLE
Show code coverage in PR

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/I-Talent#460]
To have good code, we need a good code coverage. Making devs realize the code coverage in PRs is a great way to have good coverage and having tests for the code.

- Add a github bot for test coverage or something similar

**Comment by mo-5** [comment]
This looks like a good option 
https://github.com/apps/codecov

**Comment by BenJeau** [comment]
Wonder what ISED is using for that, seems like they are only free if we are opensource, which we are for now, which is good, but I think they want to make it private in the future. Meanwhile, I'll just add one of those tools. @MenaMachado is there a code coverage tool that ISED uses?

**Comment by BenJeau** [comment]
Will probably be done by the CI/CD team
