### ISSUE TITLE
Links not added to Primary Info Card on Dev

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#470]
**Describe the bug**
When filling out profile links on dev like github, linkedin, or gcconnex, the links aren't displayed on the Primary Info Card on the profile (only Email is displayed)

**To Reproduce**
1. Go to https://italent-dev.apps.dev.openshift.ised-isde.canada.ca/secured/profile/edit/primary-info
2. Enter any links into either/all form fields "GCconnnex URL" "Linkedin URL" "Github URL"
3. Press Save and go back to profile or press Save and Finish and see your profile
4. See how on Primary Info Card only the Email link is shown at the bottom

**Expected behavior**
All links that the user fills out on the Edit or Setup Profile form should be displayed on the Primary Info Card

**Screenshots**
![image](https://user-images.githubusercontent.com/43188335/86801008-972df480-c041-11ea-9347-752940401873.png)

<img width="689" alt="Screen Shot 2020-07-07 at 10 53 31 AM" src="https://user-images.githubusercontent.com/43188335/86799581-1b7f7800-c040-11ea-93d5-66fdad2bc1ae.png">

**Comment by BenJeau** [comment]
Good catch! I'll have a PR up real quick
