### ISSUE TITLE
Remove "warning" message for Private Group and Private 

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#487]
**The problem**
Warning messages should be reserved for very important notices. Overuse of warning messages, especially if they look the same can minimize their impact and people will start ignorning them. What's most important is that people are warned before they make their data public. 

**Solution**
Preference is to remove the warning message for "private group" and private buttons.  The description of the button (example private group) is understood.

**Comment by mo-5** [comment]
@KateAThornley I just noticed I have already finished the tickets (#487 and #484) related to connections this morning on my branch. Do you mind if I assign you another ticket?
