### ISSUE TITLE
Add "general search" in top nav bar next to the I-Talent  

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#488]
**Is your feature request related to a problem? Please describe.**
It would be useful to search for someone or something from anywhere on the site.  For example, if I want to add a connection to my private group, I need to go to the search page to find the profile. It would be quicker to search for someone from the edit page.  The general search should at least work for now in terms of finding someone's profile. We can also improve it later for specific name searches. 

**Describe the solution you'd like**
Add "search field" to top nav bar, next to I-Talent. 

**Additional context**
![image](https://user-images.githubusercontent.com/49656364/86975966-7a7be480-c147-11ea-930c-0e2fd6750248.png)

**Comment by BenJeau** [comment]
Here's a few mockups
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/22248828/87802339-0b754e80-c81f-11ea-845a-100c81db87f2.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/22248828/87802341-0ca67b80-c81f-11ea-93d0-c520db7a2e27.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/22248828/87802345-0d3f1200-c81f-11ea-949c-75c81fd24fff.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/22248828/87802346-0dd7a880-c81f-11ea-9ef2-e8e237ca005b.png)

**Comment by BenJeau** [comment]
![image](https://user-images.githubusercontent.com/22248828/87802636-76268a00-c81f-11ea-900a-8e4b4bcd76fd.png)

**Comment by MenaMachado** [comment]
Hi Ben, it looks good and I think I now prefer the rounded ends.
