### ISSUE TITLE
Getting error message when adding experience to profile

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#492]
**Describe the bug**
I get an error message (see image below) when I go to add experience to my profile. 

**To Reproduce**
1. Go to 'Experience"
2. Complete all mandatory fields for Experience 2 (Experience 1 was created during initial set up)
3. Click on save and finish

**Screenshots**
![image](https://user-images.githubusercontent.com/49656364/86977362-70a7b080-c14a-11ea-8858-9eb4a8bfbdb1.png)

**Comment by BenJeau** [comment]
This should be an easy fix, just need to update the backend validator for that endpoint

**Comment by MenaMachado** [comment]
I just tried again and was able to save my 2nd experience.  However for fun, I noticed that it accepts any date.  The From date should also preceed the To date.

![image](https://user-images.githubusercontent.com/49656364/86979477-73f16b00-c14f-11ea-9f4a-5d7393ea0055.png)

**Comment by BenJeau** [comment]
Oh and also, in the OL form you can specify a grading date in the future, which doesn't make sense. Should probably open another issue

**Comment by MenaMachado** [comment]
Trevor is updating the OL card,  he's correcting it to "expiry date" which can be past or future.
