### ISSUE TITLE
When clicking on user link getting invalid profile url

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#493]
When clicking on any of the following links I get invalid profile URL 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to profile 
2. Click on GitHub, Linkedin, or GCconnex 

**Expected behaviour**
Should direct you to the link on a new page 

![image](https://user-images.githubusercontent.com/21133129/86977749-53bfad00-c14b-11ea-99dc-39b07b23f441.png)

**Comment by BenJeau** [comment]
Related to #453, should this be closed?

**Comment by mo-5** [comment]
oh didn't notice yes I will close it
