### ISSUE TITLE
Test, identify and ensure IE functionality is identical to chrome

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#498]
**Describe the bug**
The applications works in IE but sometimes there are issues in IE that are not in chrome. 

**To Reproduce**
Thoroughly test all functions in IE for any unexpected issues. 

Example of issue:
In IE, when editing the substantive from Indeterminate to term or student, it did not save the changes. 

**Screenshots**

![image](https://user-images.githubusercontent.com/49656364/87051630-d25d2e80-c1cd-11ea-895c-41ee0261de5b.png)

**Comment by mo-5** [comment]
Do we know what is the version If IE installed on work computers?

**Comment by MenaMachado** [comment]
Internet Explorer 11

**Comment by MohamedRadwan** [comment]
I think this issue has been addressed and all functionalities on chrome are the same as IE. Please reopen the ticket if you find the issue reoccurring.
