### ISSUE TITLE
Update frontend node js packages 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#503]
The following packages need to be updated and tested: 

- @ant-design/compatible         ^1.0.2  →    ^1.0.4 
- @ant-design/icons              ^4.0.5  →    ^4.2.1 
- @reduxjs/toolkit               ^1.3.6  →    ^1.4.0 
- @sentry/browser               ^5.15.5  →   ^5.19.1 
- @testing-library/jest-dom       5.8.0  →    5.11.0 
- @testing-library/react        ^10.0.4  →   ^10.4.5 
- @testing-library/user-event    10.3.2  →   12.0.11 
- antd                           ^4.1.4  →    ^4.4.1 
- bizcharts                      ^3.5.8  →    ^4.0.9 
- customize-cra                  ^0.9.1  →    ^1.0.0 
- history                       ^4.10.1  →    ^5.0.0 
- keycloak-js                   ^10.0.1  →   ^10.0.2 
- less                          ^3.11.1  →   ^3.11.3 
- less-loader                    ^5.0.0  →    ^6.2.0 
- lodash                       ^4.17.15  →  ^4.17.19 
- moment                        ^2.24.0  →   ^2.27.0 
- query-string                  ^6.12.1  →   ^6.13.1 
- react-app-rewired              ^2.1.5  →    ^2.1.6 
- react-intl                     ^4.5.5  →    ^5.0.2 
- react-scripts                   3.4.0  →     3.4.1 
- eslint                          6.8.0  →     7.4.0
- eslint-config-airbnb           18.1.0  →    18.2.0
- eslint-config-node             ^4.0.0  →    ^4.1.0
- eslint-plugin-import          ^2.20.2  →   ^2.22.0
- eslint-plugin-jsx-a11y          6.2.3  →     6.3.1
- eslint-plugin-prettier         ^3.1.3  →    ^3.1.4
- eslint-plugin-react           ^7.20.0  →   ^7.20.3
- eslint-plugin-react-hooks      ^4.0.2  →    ^4.0.6

**Comment by BenJeau** [comment]
related #315
