### ISSUE TITLE
(In IE) In the Admin Dashboard user table, changes to status are not updating in the front end

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#504]
In IE, Admin page, user table the updates to profile status are not updating on the front end but look like they are updating on the backend.  You can see the updates on the front end in Chrome. 

**To Reproduce**
1. Go to IE, Admin Dashboard,
2. Go to Users table
3.  Change profile status for a User
4. click apply, then update
5. See successful message
6.  Change not visible 

Screenshot in IE
![image](https://user-images.githubusercontent.com/49656364/87080413-a05fc280-c1f5-11ea-8ff2-d10d621dfd80.png)

Screenshot in Chrome
![image](https://user-images.githubusercontent.com/49656364/87080489-bf5e5480-c1f5-11ea-90e5-285a86bcf482.png)

**Comment by BenJeau** [comment]
Can't seem to be able to reproduce in development

**Comment by MenaMachado** [comment]
Hi Ben, in IE, I just tried to change Ali's status from Active to Inactive. I clicked on apply. I got the "are you sure you want to update" message. I clicked Update and it didn't apply the change.

**Comment by BenJeau** [comment]
This is so weird, it somehow works for me, I suppose the problem is still there

**Comment by MenaMachado** [comment]
This is the same issue in IE that's happening I think with all updates.  I think edit/save made in IE is updating in the back but not in the front.  Here's a snapshot from IE and Chrome when I made Ali's profile inactive

![image](https://user-images.githubusercontent.com/49656364/88846441-a3761f00-d1b3-11ea-963b-6483cfd9c341.png)

![image](https://user-images.githubusercontent.com/49656364/88846540-c1dc1a80-d1b3-11ea-969c-90b60ad52dd0.png)

**Comment by BenJeau** [comment]
I'll implement #448 just for this API call and deploy that branch to openshift to see if it works. I will an leave update in this issue

**Comment by BenJeau** [comment]
It seems like an issue IE has been having for a little while, https://www.computerworld.com/article/2693447/ajax-requests-not-executing-or-updating-in-internet-explorer-solution.html, it seems IE caches API calls aggressively, #448 would not fix this

**Comment by MenaMachado** [comment]
noted
