### ISSUE TITLE
In IE, save and finish function not working on Employment Data card in Edit profile

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#506]
**Describe the bug**

Changes to employment data in any field are not saving

1. Go to 'Edit Profile, Employment data'
2. Update fields
3. Scroll down to 'save and finish
4. Changes are not saving

**Comment by MenaMachado** [comment]
It looks like the save and finish is not working in any of the forms

**Comment by BenJeau** [comment]
This bug is weird, since it works with local development but not on the server
