### ISSUE TITLE
Make dashboard of Top 5 items visibile to all members of I-Talent

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#526]
**Is your feature request related to a problem? Please describe.**
The charts can be seen only by Adminstrators. HR requested that all users can see the information.

We need to decide where to best place the chart/dashboard

**Comment by BenJeau** [comment]
Do we have an idea where to put the graphs for the public to see? Maybe a new page accessible in the dropdown or from the search page? or have the option to somehow toggle it in the search page (but I think the search page should be strictly used for search)?

**Comment by MenaMachado** [comment]
I agree with the first suggestion - a new page accessible in the dropdown
