### ISSUE TITLE
Add breadcrumbs or back button to Profile pages

### ISSUE THREAD

**Issue by KateAThornley** [CDH-Studio/I-Talent#535]
**Is your feature request related to a problem? Please describe.**
Some users may want to navigate back to the results page from inside the app (not using the browser's back button), when theyve clicked on a profile card

**Describe the solution you'd like**
A solution would be either to use breadcrumbs on user profiles next to the Profile header (to the right), or a back button next to the Profile header.

**Comment by BenJeau** [comment]
Just tried putting breadcrumbs in the application, but I think it looks silly considering how simple they are or maybe that is just me. I think at most there will be three or four

![image](https://user-images.githubusercontent.com/22248828/99346968-ded05280-2863-11eb-85f8-e37505031c48.png)

And if we would have breadcrumbs, I think it would be on the following pages/cases (and other variations)

- If users are on their profile, and they go to edit their profile
  - `Profile / Edit profile`
- If users are on the home page, search
  - `Home / Search profiles`
- If users are on the home page, search, then click on a profile
  - `Home / Search profiles / Profile`
- If users are on the home page, search, click on a profile, and if they are on their profiles, edit their profiles
  - `Home / Search profiles / Profile / Edit profile`
