### ISSUE TITLE
Start the process to converting backend from Javascript to Typescript

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#563]
Start the setup process to convert the backend from Javascript to Typescript. Typescript will offer better support to the project with type checking and better error handling. This would be the best way to catch bugs before deploying code.

**Comment by mo-5** [comment]
This is a very low Priority I think it would just be good to implement. I just opened the ticket to not forget about it.

**Comment by BenJeau** [comment]
I'm starting to convert the backend to typescript
