### ISSUE TITLE
In the profile, when you hover over the pencil it says "private" instead of edit

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#570]
**Describe the bug**

In the profile, when you hover over the pencil it says "private" 

**Expected behavior**
It should say, "edit" everywhere the pencil is used 
 
**Screenshots**
![image](https://user-images.githubusercontent.com/49656364/88313890-27c33080-cce2-11ea-9c44-6c72eda09c45.png)

**Additional context**

**Comment by BenJeau** [comment]
fixed by #569
