### ISSUE TITLE
Increase size of changes saved success message

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#615]
**Is your feature request related to a problem? Please describe.**
When you save changes in edit profile, you get a success message.  This message appears close to the search field and is a little small. 

**Describe the solution you'd like**
I think we should increase the size of the message and perhaps have it slide in from the right above employee summary card where it is more visible. 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/49656364/88850472-7167bb80-d1b9-11ea-90bc-b8fa4a3c3319.png)

**Comment by BenJeau** [comment]
I aggree, we should change all of those message sizes throughout the application. Maybe its as simple as modifying its CSS?

**Comment by MenaMachado** [comment]
We should standardize the size of the messages.

**Comment by BenJeau** [comment]
If I'm not mistaken, this is not fixed, #720 only introduced it in a couple of places, but not everywhere in the app. Right @dynamic11 ?

**Comment by dynamic11** [comment]
The issue is related to "save success" message on profile. I updated the notification there. However, we still need to do the rest of the app.

**Comment by dynamic11** [comment]
I have opened new issue that covers rest of the app (#784 ) @BenJeau
