### ISSUE TITLE
Users are able to enter any character for first and last name

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#617]
**Describe the bug**
1. user can provide any first and last name.  You are able to change your name to anything including a space or numbers

**To Reproduce**
- Navigate to My Profile -> General Profile Info -> Edit Profile

**Expected behavior**
We should set some rules for first and last name. 

**Describe the bug**

2. Note that your profile name and picture does not update with these changes

**To Reproduce**
- Navigate to My Profile -> General Profile Info -> Edit Profile
- Change Name
- Save and Finish

![image](https://user-images.githubusercontent.com/49656364/88852097-c73d6300-d1bb-11ea-9435-c0ce69d7338a.png)

**Comment by BenJeau** [comment]
What characters should we allow the user to enter? Only letters (including french ones) and "-"? Or more than that

**Comment by MenaMachado** [comment]
Yes, I think that would work.

**Comment by BenJeau** [comment]
Also, do we want the name in the dropdown to be the same as the one in their profile?

**Comment by MenaMachado** [comment]
Sorry, what do you mean by name if the dropdown?  Do you mean the menu at the top.  I would say yes
