### ISSUE TITLE
Make search dark box same color as navigation bar

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/I-Talent#629]
**Is your feature request related to a problem? Please describe.**
make the search box same color as nav

**Describe the solution you'd like**
make the search box same color as nav

![image](https://user-images.githubusercontent.com/11470442/88972954-5f068400-d284-11ea-8c9a-7022a70740b0.png)

**Comment by BenJeau** [comment]
I would even make the navBar background transparent in the search view (that view) to put more enphasis on the search (but you'll need to remove the shadow and make the items in the navbar darker instead of the current white)
