### ISSUE TITLE
Show visibility setting (image) on top right of card to all users

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#656]
**Is your feature request related to a problem? Please describe.**

Users need to view visibility settings for each card aside from greyed area. 
Also, administrators can view all sections and all profile.  

**Describe the solution you'd like**

- When visibility is set to hidden, hide the content of the card but keep the heading with the selected privacy settings image on the card. 
- Continue to use greyed section for additional visible cue.

**Comment by BenJeau** [comment]
@MenaMachado For this, would you like to simply show the visibility toggles, but just make them disabled/not clickable?
