### ISSUE TITLE
Make "Project" a subsection of Experience

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#673]
**Is your feature request related to a problem? Please describe.**
Projects shall be associated with specific jobs for ease of reference and indication of dates/role.

#435 

**Describe the solution you'd like**
For each Experience (Experience: 1):
In the Edit form, below the Description box add a field and box called Projects where Users can add their list of projects 
Project does not need it's own privacy setting
Project shall be a searchable item

![image](https://user-images.githubusercontent.com/49656364/89472704-084eed80-d74f-11ea-96aa-38b0985e4dee.png)

![image](https://user-images.githubusercontent.com/49656364/89472798-3cc2a980-d74f-11ea-872f-cd7d3da8ada7.png)

**Comment by mo-5** [comment]
I could work on this issue since it would be part of the files I am modifying. What do you think @BenJeau ?

**Comment by BenJeau** [comment]
I agree, I'll let you do it
