### ISSUE TITLE
As an administrator, I need to be able to delete accounts

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#675]
**Is your feature request related to a problem? Please describe.**
When employees leave, we need to be able to delete accounts to remove redundant data related to that user. 

**Describe the solution you'd like**
On the Admin Dashboard, there should be an option added to the status called "delete".

When the user is deleted, it shall delete all data related to the user including the user's profile. Links to that user's profile should no longer work.

**Comment by mo-5** [comment]
related to #175
