### ISSUE TITLE
Issue with format for information entered in description box in Experience Section of user profile

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#676]
**Describe the bug**
There seems be be an issue with formatting the information entered in the description box, particularily with bullets. 

Screenshot from user profile page

![image](https://user-images.githubusercontent.com/49656364/89554271-a4730600-d7dc-11ea-81b1-ac385cab7e08.png)

#575

**Comment by TrevorBivi** [comment]
This bug seems related to how css styling is handling tab characters

Word breaking seems to really like breaking at tab characters when a line is too long
![sizing](https://user-images.githubusercontent.com/30152653/89566556-5c5cdf00-d7ee-11ea-80ff-7db6e0adc110.png)
