### ISSUE TITLE
Modifiy and resolve issue with date fields for Education

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#677]
**Describe the bug**

The end date selected in the edit profile page does not match the end date displayed in user profile.  It seems to consistently display the preceding month. 

If you enter April 2020, it displays March 2020. 

Also, in user testing, some users preferred not to include the dates they graduated over concerns of bias. 

And most users have graduated but the end date for  I-Talent defaults to ongoing. 

To resolve:

- Fix end date issue
- Remove mandatory requirement for education dates
- Remove default to ongoing

**Screenshots**
![image](https://user-images.githubusercontent.com/49656364/89555740-6e368600-d7de-11ea-83c0-224a4cc6f18f.png)
![image](https://user-images.githubusercontent.com/49656364/89556036-cf5e5980-d7de-11ea-9b58-9bc8fcb00501.png)

**Comment by MenaMachado** [comment]
similar to #681

**Comment by BenJeau** [comment]
I'll take over this issue, if its fine with you @TrevorBivi, I think its related to one of my change..

**Comment by BenJeau** [comment]
The dates are still required and the checkbox is still checked. I've started working on implementing this
