### ISSUE TITLE
Add third option for new users to sign in but skip profile creation and go directly to search page

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#678]
**Is your feature request related to a problem? Please describe.**

Users (Managers) will want to use I-Talent to search for employees for staffing positions. They may not have the time to create a profile and we want to encourage the use of the application. 

Currently, the app is designed to encourage profile creation and so they are taken through the steps to create a profile. Managers are forced to go through every step, by clicking save and next until done, leaving all sections empty until done.  Managers can find this cumbersome. 

**Solution**

On the welcome page, add a third option (button) for users (Managers) at first login to go directly to the search profiles. They would skip the profile creation page. 

Can we add the same "search profiles" button as when profile all done on the Welcome page?

![image](https://user-images.githubusercontent.com/49656364/89557400-be164c80-d7e0-11ea-8327-96b895aca9bb.png)

![image](https://user-images.githubusercontent.com/49656364/89559332-865cd400-d7e3-11ea-81d5-c3c23b58e29e.png)

**Comment by BenJeau** [comment]
We can add that option, they would still have a profile, just an empty one (if thats ok). The only information that the user needs to enter right now is the office location, I guess we can make it optional in the forms.

**Comment by BenJeau** [comment]
What I would do is just save in their profile that they've completed the signup process ONLY when they click on that button (if its good), since how the routing works

**Comment by MenaMachado** [comment]
Ok, let's do that.  However we need to have a separate discussion on the visibility of profiles with no data or lots of empty sections.

**Comment by BenJeau** [comment]
What we could do is utilise the three profile status that we have.

**ACTIVE** - Default profile status 
**INACTIVE** - Set by an admin
**HIDDEN** - Set by the user itself

Inactive and hidden would effective do the same thing, but would be triggered in different ways.

I know this only handles part of your worry, but I think the user should be able to hide their profile. And this setting could be set in the new settings section I'm creating right now to add a place to delete your profile.

**Comment by MenaMachado** [comment]
I like the idea, in fact, I had proposed it with the original team but at the time they didn't know how to implement it. They weren't sure how to distinguish the 2 in the system.  

If a user selects hidden, will the Admin see "hidden" in status

**Comment by MenaMachado** [comment]
If we implement "hidden" status as suggested, the users profile shoiuld not appear in search results.  However, HRB should be able to see all sections. We would advise people in the privacy policy.  Also, I think we should allow users to delete their profiles. I just need to confirm with HRB first. 

If a user skips profile creation, can I-Talent automatically give them "hidden" status?

**Comment by BenJeau** [comment]
Yes, it can automatically be given. Also, I'm adding the option for users to delete their accounts here https://github.com/CDH-Studio/UpSkill/pull/682

**Comment by BenJeau** [comment]
And the visibility part, there's already an issue open https://github.com/CDH-Studio/UpSkill/issues/639

**Comment by MenaMachado** [comment]
When you work on this ticket can you make the following edits to the Welcome sentence. 

Edit the sentence to " Please select GCdirectory profile to autofill your organization and contact information or you can start from scratch and sync with GCdirectory later to retrieve your organization information.

GEDS was officially renamed to GCdirectory / GCannuaire (in FR)

https://gcdirectory-gcannuaire.ssc-spc.gc.ca/en/GCD/?pgid=002
