### ISSUE TITLE
Add Links to Learning and Development Card

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#703]
- Employee will want to add/edit/delete links to documents related to L&D
- Links can be external or internal
- Links shall be assigned to a category. The categories are: learning and development plan, certificates, other
- Employees will need to be able to add a title of document and URL to document.

**Comment by BenJeau** [comment]
@MohamedRadwan I think you should probably do this, since you're already working on the links?

**Comment by mo-5** [comment]
Yes I can take care of this ticket
