### ISSUE TITLE
User cannot leave Job Mobility fields blank

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#706]
A user may not want to provide a response for job mobility. 

Open to working remotely field:
If I switch from yes or no, it will save the changes correctly.  However, if I want to leave it blank on the edit form and save, it will not apply the change on the profile page, it will revert to the previous selected item. It doesn 't seem to accept a blank field. 

It is the same issue with the field for  "Looking for new job" 

Willing to relocate to is working properly

![image](https://user-images.githubusercontent.com/49656364/89677954-533a4380-d8bc-11ea-8195-c60f95bc11fe.png)

**Comment by BenJeau** [comment]
I have an idea why its doing that, when we switched to the new backend, everywhere in the forms it was like that - thought we fixed every input. I can take over this if you'd want

**Comment by MenaMachado** [comment]
go ahead. Thank you

**Comment by MenaMachado** [comment]
While you're in this section of the code, can you change the edit page wording for the labels to the following or does the wording have to match the profile page?

Are you open to working remotely?
If you are willing to relocate, select your preferred locations
Are you actively looking for a new job?
