### ISSUE TITLE
I am available to be a mentor is not saved

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#708]
**Describe the bug**
When you toggle I am available to mentor it is not saved. 

**To Reproduce**
1. Go to edit profile competencies and skills 
2. Click on I am available to mentor 
3. Refresh the page
4. The toggles return to false

![image](https://user-images.githubusercontent.com/21133129/89681871-c5625680-d8c3-11ea-9b3d-36d84e9e6895.png)

After refresh 

![image](https://user-images.githubusercontent.com/21133129/89681892-cd21fb00-d8c3-11ea-8103-27a6a04ba149.png)

**Comment by dynamic11** [comment]
I found the fix for this issue. Will test and out in PR.
It is saving but we are not toggling the form correctly on form load.
