### ISSUE TITLE
Can't unselect expired button on OL card and consequently issue with toggle switch. 

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#742]
**Describe the bug**
It seems the expired button is selected and when you try to remove the selection, it doesn't remove it when you save and finish.  If you entered a date and try to unselect it, the date saves but the expired button stays selected.

Also, I can't untoggle even when I delete the results. 

I'm getting a "sucessfully saved" message. 

Could this issue be similar to the one we were having with the job mobility card?

**Screenshots**

![image](https://user-images.githubusercontent.com/49656364/89899437-4d8c7880-dbb0-11ea-963d-143fd4a88e19.png)

**Comment by BenJeau** [comment]
the toggle bug is fixed here #741
