### ISSUE TITLE
Create profile page is not styled 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#755]
**Describe the bug**
The design to the creat profile page step 1 is not applied 

**To Reproduce**
1. Delete your database
3. Goto /profile/create/step/1

**Expected behavior**
The welcome logo to be in the middle of the card

**Screenshots**
![image](https://user-images.githubusercontent.com/21133129/90030677-5487b980-dc8a-11ea-929a-77813b1c11db.png)

**Additional context**

**Comment by BenJeau** [comment]
I'm not able to reproduce this, did you try rebuilding/restarting docker?

**Comment by mo-5** [comment]
Yeah, I tried rebuilding and it is still occurring. I will close this issue for now since it's not reproduced it might be local
