### ISSUE TITLE
Test Drupal - Content Management System for HR to add content to I-Talent

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#757]
**Is your feature request related to a problem? Please describe.**

Implement a CMS to enable HR to update and edit content on I-Talent

**Describe the solution you'd like**
Drupal would allow HR to update the following sections:
About I-Talent
Privacy 
Terms and Conditions of Use
Help/FAQs

**Comment by dynamic11** [comment]
I have set up the drupal site.
URL: https://i-talent-ciodrcoe-dev.apps.dev.openshift.ised-isde.canada.ca/en

 **To Do:**
-as how i can fix the logo stretch issue ( i need the dimensions of the logo that the theme expects)
- i need the content (English and French)

**Comment by mo-5** [comment]
The drupal urls have been updated:

https://italent-uat-cms-studioup-dev.apps.dev.ocp-dev.ised-isde.canada.ca/en

https://italent-dev-cms-studioup-dev.apps.dev.ocp-dev.ised-isde.canada.ca/en
