### ISSUE TITLE
Org chart not showing on profile

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/I-Talent#788]
**Describe the bug**
Org chart not showing on profile. Issue is only on development. UAT is working which means it broke from August 8th onwards.

![image](https://user-images.githubusercontent.com/11470442/90541342-7aacce00-e150-11ea-91e6-aea9d1daccf4.png)

**Comment by BenJeau** [comment]
Locally they still display on the Mary Doe profile, but not when you sync with GEDS, I suppose its something related to GEDS
