### ISSUE TITLE
Inform the user that section of the profile are set to hidden instead of no information available 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#797]
**Describe the bug**
Instead of showing to the user that content is not provided, we should display content is hidden 

![image](https://user-images.githubusercontent.com/21133129/90789387-ddc76d80-e2d4-11ea-9f5e-83903bf4002a.png)

**Comment by BenJeau** [comment]
This has been fixed by #814, right @dynamic11?

**Comment by dynamic11** [comment]
Yes
