### ISSUE TITLE
When viewing own profile, the visibility toggle for ex-feeder is not present

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/I-Talent#816]
**Describe the bug**
The visibility toggle for the ex-feeder card is not present when viewing your profile (title pretty self explanatory)

**To Reproduce**
1. Go to 'My profile'
2. Scroll down to 'Ex-feeder' section
3. See that the toggle is not present

**Expected behavior**
The user should be able to toggle their own cards

**Screenshots**
![image](https://user-images.githubusercontent.com/22248828/91988836-c12c2c00-ecfd-11ea-8820-4cbe51325f77.png)

**Additional context**
Introduced by #814 (I think)

**Comment by dynamic11** [comment]
On it!
