### ISSUE TITLE
Fix edge cases when updating the job title

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/I-Talent#819]
**Describe the bug**
When updating the job title, often times it will not properly update or create it and may overwrite it in the other language - it is just not an overall good experience.

**Additional context**
The way that the job title is being updated is a bit "hacky" and is not respecting the language of that API call. In the backend, when updating a profile, the call needs to specify the language, but when GEDS and, subsequently, the job title, it is passing both the English and French data in the same call - which should be done in two separate calls, to respect the original backend API structure.

The correct way to fix this would be to also alter the GEDS update profile call to only send the data in the appropriate call language specified, instead of both in the same call. This creates complexity in the backend and makes it less readable.

**To Reproduce**
Play with updating the job title in the forms

**Expected behavior**
For it to be properly saved

**Comment by dynamic11** [comment]
- remove the item from the form until issue is resolved with API
- just accept the title that is coming from GC directory
