### ISSUE TITLE
The URL attachment field input is not very responsive

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/I-Talent#821]
**Describe the bug**
When inputting text in the URL field input, you can see that the webpage is not responding fast - I think this is something related to the `findErrorTabs()` function, since it is not doing a deep equals check.

**To Reproduce**
1. Go to 'Edit profile'
2. Click on 'Qualifications'
3. Enter a new URL

**Expected behavior**
For the field to be as responsive as the other fields

**Additional context**
https://github.com/CDH-Studio/UpSkill/pull/720

**Comment by BenJeau** [comment]
![Peek 2020-09-08 17-54](https://user-images.githubusercontent.com/22248828/92531558-86922a00-f1fc-11ea-8bca-d72ca5930df4.gif)

For some context - the url field for some reason re-renders the whole screen for every input change, but not on the other fields (re-renders are shown via the borders)

**Comment by BenJeau** [comment]
Looking more closely, the `findErrorTabs()` gets triggered 3 times when modifying the url field, the 2nd time it clears the state (`tabErrorsBool`) and the third time, the field error is back

**Comment by BenJeau** [comment]
The PR fixing it seems to be bringing more bugs than expected

**Comment by mo-5** [comment]
This issue is no longer occurring. Closing the ticket, please reopen it if you notice an issue.
