### ISSUE TITLE
Set up PostgreSQL database in AWS 

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#828]
Once we are properly set up with Jenkins, we need to move forward with setting up the database from openshift to AWS. 

https://wiki.ised-isde.canada.ca/display/RDADC/Options+for+using+a+database+in+the+Cloud

Size - 20GB Storage, 2CPU, 2GB Memory

**Comment by mo-5** [comment]
Dev is now on the AWS database. I am still looking at retrieving all the data. So that I could migrate the data on UAT.

**Comment by mo-5** [comment]
Moved both dev and UAT to AWS environment. I will keep the database container we have an open shift for a week or so in case we need it
