### ISSUE TITLE
Issue with Date for Expired OL language results

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/I-Talent#832]
**Describe the bug**
If you enter an expiry date and then change your mind, it will not let you leave it blank. 

The only way to work around this issue, is to toggle the switch to no, save and finish, the return to enter the results only. 

I thought we had resolved this issue, but it looks like it's back. 

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/49656364/92285178-aad6c980-eed1-11ea-85db-0c41be4c0049.png)

**Comment by BenJeau** [comment]
I was not able to reproduce the bug locally in dev - where did you encounter the bug?

**Comment by MenaMachado** [comment]
Actually, it's working fine.  I tried to delete the date using the delete button and that's why I thought it didn't work.  I just noticed that if you hover over the date or calendar, the X appears and if you click the x, you can delete the date.

**Comment by MenaMachado** [comment]
Actually, there might be an issue. it won't save the change - I'm getting  "Data not saved due to network error", after I delete the expiry date for Reading result, and click on save and finish.  
![image](https://user-images.githubusercontent.com/49656364/92523960-49736b00-f1ef-11ea-8736-2b40a09cf9d9.png)

**Comment by BenJeau** [comment]
I can reproduce it locally, let me look at it
