### ISSUE TITLE
Unable to edit and change the visibility of experience and education cards

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/I-Talent#842]
**Describe the bug**
Unable to change the visibility of the experience and education cards. It looks like the card doesn't take the user as the owner of the profile. 
**To Reproduce**
1. Go to profile 
2. Try to edit the cards 

**Expected behavior**
The user has the ability to modify the experience and education cards as well as the visibility of the cards.

**Screenshots**
![image](https://user-images.githubusercontent.com/21133129/92677807-9d1aad00-f2f2-11ea-85ad-a4b147441d49.png)

**Additional context**

**Comment by dynamic11** [comment]
I may have intoduced this bug so let me look into it. Are you seeing this in local or dev server?

**Comment by BenJeau** [comment]
I see it both locally and on the server
