### ISSUE TITLE
Unchecked runtime.lastError

### ISSUE THREAD

**Issue by SukhsimranpreetSekhon** [CDH-Studio/I-Talent#847]
**Describe the bug**
The application gets an unchecked error for the message port being closed before a response was received (runtime.lastError).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to my profile page.
2. Click on chrome dev tools.
3. Scroll down to the first error on the console.
4. See error.

Note: Error appears for other pages too.

**Expected behaviour**
No errors coming from the console.

**Screenshots**
![runtime lastError](https://user-images.githubusercontent.com/35780281/92774280-4f8e5680-f36b-11ea-9d2c-4353df59d2e7.jpg)

**Additional context**

**Comment by BenJeau** [comment]
I'm not able to reproduce on my side, either locally or on the servers. @SukhsimranpreetSekhon are you able to reproduce it again now?
