### ISSUE TITLE
React does not recognize the "Landing" and "Page" props on specific DOM element(s)

### ISSUE THREAD

**Issue by SukhsimranpreetSekhon** [CDH-Studio/I-Talent#872]
**Describe the bug**
React does not recognize the "Landing" prop on a specific DOM element. This error warning also appears for the "Page" prop for a specific DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase "landing" and "page" instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Main Page of the Web Application.
2. Click on Chrome Dev Tools.
3. Scroll down to warning errors.

**Expected behaviour**
Needs both errors removed before the launch.

**Screenshots**
![Landing prop](https://user-images.githubusercontent.com/35780281/93233733-6e189700-f749-11ea-9ebd-ca9dd62f60ee.jpg)
![Page prop](https://user-images.githubusercontent.com/35780281/93233746-71ac1e00-f749-11ea-9113-a40879bd1d3a.jpg)

**Additional context**

**Comment by BenJeau** [comment]
Error shown in the logs points to https://github.com/CDH-Studio/UpSkill/blob/development/services/frontend-v3/src/components/layouts/landingLayout/LandingLayoutView.jsx#L63, which should be a simple fix. The `Landing` and `Page` prop for the `<h1 />` tag should not be present
