### ISSUE TITLE
Two GET Requests to ISED intranet not found resulting in 404 abort

### ISSUE THREAD

**Issue by SukhsimranpreetSekhon** [CDH-Studio/I-Talent#873]
**Describe the bug**
1st GET Request: GET https://www.ic.gc.ca/auth/resources/4.8.3.final/login/ised-intranet/js/transitions.js
2nd GET Request: GET https://www.ic.gc.ca/auth/resources/4.8.3.final/login/ised-intranet/js/faqpolyfill.js
Both requests not found and aborted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Sign-In Page of the Web Application.
2. Click on Chrome Dev Tools.
3. Scroll down to warning errors.

**Expected behaviour**
Need to find out what these get requests are pointing to and see if they are really needed. Need to be fixed in order to have no errors for the sign-in page.

**Screenshots**
![get issues](https://user-images.githubusercontent.com/35780281/93243090-b2119900-f755-11ea-8dfb-1f44460dc856.jpg)

**Additional context**
Might be an API based issue where the get request is pointing to the wrong endpoint.

**Comment by BenJeau** [comment]
I think these errors are out of our control. What do you think @dynamic11? Maybe we could notify Matthew?

**Comment by BenJeau** [comment]
Closing this since we can't do anything about it
