### ISSUE TITLE
Sign-in page: send cookie(s) in cross-site request(s)

### ISSUE THREAD

**Issue by SukhsimranpreetSekhon** [CDH-Studio/I-Talent#874]
**Describe the bug**
Under the issues tab of Chrome Dev Tools, there is a suggestion/issue for whether to send a cookie in a cross-site request by specifying its SameSite attribute. It is asking to specify the cookie's behaviour as it is right now diverting to its default stage that prevents the cookie from being sent in a cross-site request. This behaviour protects user data from accidentally leaking to third parties and cross-site request forgery. Even if we want this, it still wants us to specify using the suggested ways instead. Can get further information on the Chrome Dev Tools console.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Sign-In Page of the Web Application.
2. Click on Chrome Dev Tools and hit the blue comment icon/issues button on the top menu.
3. Should show console, after clicking on the icon, on the bottom.
4. See two cookie issues/suggestions in the console.

**Expected behaviour**
Do not know if we need to address this issue. However, might be important for further implementation later.

**Screenshots**
![1st SameSite Cookies](https://user-images.githubusercontent.com/35780281/93247099-c9538500-f75b-11ea-85a2-5f35faa4189f.jpg)
![2nd SameSite Cookies](https://user-images.githubusercontent.com/35780281/93247114-cc4e7580-f75b-11ea-8a62-9370c5383231.jpg)

**Additional context**

**Comment by BenJeau** [comment]
I think if this warning is shown locally and not on the server, its not a great deal (I think this is shown since the keycloak cookie is not made from the same domain locally from the server/client domain - which is localhost locally and not canada.ca, but I may be wrong). @dynamic11 what do you think? Also, @dynamic11 I thought CSRF was handled?
